name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t yourusername/nextjs-app .
        docker push yourusername/nextjs-app

    - name: SSH to Server and Deploy
      uses: appleboy/ssh-action@v0.5.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          docker pull yourusername/nextjs-app
          docker stop nextjs-app || true
          docker rm nextjs-app || true
          docker run -d -p 3000:3000 --name nextjs-app yourusername/nextjs-app
